### ISSUE TITLE
not an issue, a question

### ISSUE THREAD

**Issue by SuperNeotendo** [rpsubc8/ESP32TinyC64#2]
what about to create an 1541 emulator like the pi1541, you are already emulating 6502 and CIA, would it not be possible to emulate 6502 and VIA, what do you think?

**Comment by rpsubc8** [comment]
Both the Toy C64 and the Emudore are excessively slow, for now. They are just sketches, which will be further polished and optimised over time.
The Toy C64 has a basic disk emulation, but it consumes few resources, it is more about speed than precision, so it is unlikely that something similar to the pi1541 will be included, at least in the short term.

**Comment by SuperNeotendo** [comment]
i do not mean include it into the C64 emulator, create an standalone 1541 emulator without the C64 stuff. use function pointers to speedup opcode execution, use multitasking and maybe freertos on esp32.

here is my first sketch as a study
https://github.com/SuperNeotendo/esp1541
