### ISSUE TITLE
Errors in Arduino IDE

### ISSUE THREAD

**Issue by AxelAhlborn** [rpsubc8/ESP32TinyC64#3]
I get errors when using the Arduino IDE. Tried both versions: 1.8.11 and 1.8.19.

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z13SDL_keys_pollv+0x8): undefined reference to `CIA1::TestTeclado(unsigned char, unsigned char)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0x28): undefined reference to `vtable for CIA1'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0x2c): undefined reference to `vtable for CIA2'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0x94): undefined reference to `Memory::AssignPtrMemory(unsigned char*)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0x98): undefined reference to `CPU6502::AssignPtrMemory6502(unsigned char*)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0x9c): undefined reference to `VIC::VIC(CPU6502&, Memory&, HostIO&)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0xa0): undefined reference to `VIC::AssignPtrRegs(unsigned char*)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0xa4): undefined reference to `Memory::ReadFromFlash(unsigned char const*, unsigned short, unsigned short)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0xa8): undefined reference to `HostIO::Initialize()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0xac): undefined reference to `Memory::RegisterPeripheral(XPeripheral*, unsigned short, unsigned short)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0xb0): undefined reference to `CPU6502::Reset()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0xb4): undefined reference to `IECBus::RegisterDevice(int, IECDevice*)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0xb8): undefined reference to `CPU6502::Dump()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z5setupv+0xbc): undefined reference to `PreparaColorVGA()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z21jj_loop_cpu_one_framev+0x1c): undefined reference to `CIA::UpdateCIA()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z21jj_loop_cpu_one_framev+0x20): undefined reference to `IECBus::Update()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z21jj_loop_cpu_one_framev+0x24): undefined reference to `CPU6502::RunOpcode()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal._Z4loopv+0x14): undefined reference to `jj_video_Update()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_vga+0x8): undefined reference to `Memory::Memory()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_vga+0xc): undefined reference to `CPU6502::CPU6502(Memory&)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_vga+0x10): undefined reference to `HostIO::HostIO()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_vga+0x14): undefined reference to `IECBus::IECBus()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_vga+0x18): undefined reference to `IEC1541::IEC1541()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal.exit._GLOBAL__sub_D_vga+0x4): undefined reference to `IEC1541::~IEC1541()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:(.literal.exit._GLOBAL__sub_D_vga+0x8): undefined reference to `Memory::~Memory()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o: in function `SDL_keys_poll()':

C:\Users\axela\Documents\Arduino\c64/c64.ino:92: undefined reference to `CIA1::TestTeclado(unsigned char, unsigned char)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:93: undefined reference to `CIA1::TestTeclado(unsigned char, unsigned char)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:94: undefined reference to `CIA1::TestTeclado(unsigned char, unsigned char)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:95: undefined reference to `CIA1::TestTeclado(unsigned char, unsigned char)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:96: undefined reference to `CIA1::TestTeclado(unsigned char, unsigned char)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o:C:\Users\axela\Documents\Arduino\c64/c64.ino:97: more undefined references to `CIA1::TestTeclado(unsigned char, unsigned char)' follow

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o: in function `setup()':

C:\Users\axela\Documents\Arduino\c64/c64.ino:215: undefined reference to `Memory::AssignPtrMemory(unsigned char*)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:216: undefined reference to `CPU6502::AssignPtrMemory6502(unsigned char*)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:218: undefined reference to `VIC::VIC(CPU6502&, Memory&, HostIO&)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:219: undefined reference to `VIC::AssignPtrRegs(unsigned char*)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:224: undefined reference to `Memory::ReadFromFlash(unsigned char const*, unsigned short, unsigned short)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:225: undefined reference to `Memory::ReadFromFlash(unsigned char const*, unsigned short, unsigned short)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:226: undefined reference to `Memory::ReadFromFlash(unsigned char const*, unsigned short, unsigned short)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:228: undefined reference to `HostIO::Initialize()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:236: undefined reference to `Memory::RegisterPeripheral(XPeripheral*, unsigned short, unsigned short)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:237: undefined reference to `Memory::RegisterPeripheral(XPeripheral*, unsigned short, unsigned short)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:238: undefined reference to `Memory::RegisterPeripheral(XPeripheral*, unsigned short, unsigned short)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:239: undefined reference to `CPU6502::Reset()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:242: undefined reference to `IECBus::RegisterDevice(int, IECDevice*)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:244: undefined reference to `CPU6502::Dump()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:258: undefined reference to `PreparaColorVGA()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o: in function `jj_loop_cpu_one_frame()':

C:\Users\axela\Documents\Arduino\c64/c64.ino:297: undefined reference to `CIA::UpdateCIA()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:298: undefined reference to `IECBus::Update()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:299: undefined reference to `CPU6502::RunOpcode()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o: in function `loop()':

C:\Users\axela\Documents\Arduino\c64/c64.ino:336: undefined reference to `jj_video_Update()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o: in function `_GLOBAL__sub_I_vga':

C:\Users\axela\Documents\Arduino\c64/c64.ino:59: undefined reference to `Memory::Memory()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o: in function `__static_initialization_and_destruction_0':

C:\Users\axela\Documents\Arduino\c64/c64.ino:60: undefined reference to `CPU6502::CPU6502(Memory&)'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:60: undefined reference to `HostIO::HostIO()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:61: undefined reference to `IECBus::IECBus()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\axela\Documents\Arduino\c64/c64.ino:62: undefined reference to `IEC1541::IEC1541()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o: in function `_GLOBAL__sub_D_vga':

C:\Users\axela\Documents\Arduino\c64/c64.ino:63: undefined reference to `IEC1541::~IEC1541()'

c:/users/axela/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\c64.ino.cpp.o: in function `__gnu_cxx::new_allocator<Info6502::OpcodeInfo>::deallocate(Info6502::OpcodeInfo*, unsigned int)':

c:\users\axela\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\ext/new_allocator.h:125: undefined reference to `Memory::~Memory()'

collect2.exe: error: ld returned 1 exit status

exit status 1

Fehler beim Kompilieren für das Board ESP32 Dev Module.

**Comment by rpsubc8** [comment]
Try downloading again, I have updated the repository.
The Arduino IDE version did not support the .cc file extension in the projects. Just rename it to .cpp.
Make sure you also have Espressif System version 1.0.6.

**Comment by AxelAhlborn** [comment]
Thank you, it works. Greetings Axel
